### PR TITLE
Add symfony 5 support

### LINKED ISSUE #48: Symfony 5 support
Hi @paknahad 

Any take on supporting Symfony 5? jsonapi-bundle require `proxy-manager-bridge ^4.1` but Symfony 5 uses `"symfony/proxy-manager-bridge": "5.0.*"`

### PR DESCRIPTION
**Pull request by AlexLisenkov**
- Upgraded bundle to symfony 5
- Added php 7.4 to travis
- Updated sorting of use statements in tpl files
- Fixed coding style
- Fixed travis build

Fixes #48

### CODE REVIEW

**Comment by paknahad** [comment]
Hi @AlexLisenkov 
Thank you for your PR
There is a small problem. It seems in your PR, the permission of some files has been changed (from 644 to 755). It's your kind if you revert them to the previous one.

**Comment by AlexLisenkov** [comment]
Fixed it.

Do you want me to update the readme stating you should use version 3.0.0 and below for symfony 4?

**Comment by paknahad** [comment]
Yes that would be great. Thanks

**Comment by AlexLisenkov** [comment]
I think thats it

**Pull request merged**
